### PR TITLE
Fixed and improved logging

### LINKED ISSUE #8: App usage isn't correctly logged
Data doesn't seem to be logged correctly right now, I'm probably not handling the UsageEvents correctly.

### LINKED ISSUE #15: Fix building aw-server-rust in release-mode in CI before deploy

### PR DESCRIPTION
**Pull request by ErikBjare**
Should fix any crashes people experience...

 - [x] Fixed logging by correctly setting pulsetimes by eventType
 - [x] Automatic logging (you no longer need to press the button)
 - [x] Fix memory inefficiency when fetching events

Fixes #8 and fixes #15 (I think)

### CODE REVIEW

**Comment by ErikBjare** [comment]
Things are still not perfect, got a weird long Syncthing event for instance on my phone, even though I wasn't actively using it.

Will do some more testing, but it's a lot better now.

Also, need to fix #15

**Comment by johan-bjareholt** [comment]
So this fixes so it always syncs if I understand the code correctly?

It's hard to read this code as I have pretty much 0 understanding of aw-android otherwise.

**Comment by ErikBjare** [comment]
@johan-bjareholt Yes, it starts fetching all past events when you open the app. Not sure if it works properly if you don't open the app in a week or two, as I'm not sure if Android stores UsageEvents indefinitely.

**Comment by ErikBjare** [comment]
@johan-bjareholt Apparently the UsageEvent store doesn't keep more than "a few days of data". So we'd need some regular background service to do this properly, not just run it on start.

**Pull request merged**
